# This file is generated by setuptools_scm
# DO NOT EDIT!

__version__ = version = '0.0.0'  # Will be replaced by setuptools_scm
__version_tuple__ = version_tuple = (0, 0, 0)  # Will be replaced by setuptools_scm
