# This file is generated by setuptools_scm
# DO NOT EDIT!

__version__ = version = '0.0.0'  # Fallback version if SCM version cannot be determined
__version_tuple__ = version_tuple = (0, 0, 0)  # Fallback version tuple
